### ISSUE TITLE
Include Git

### ISSUE THREAD

**Issue by battlemidget** [juju-solutions/reactive-base-layer#7]
Git seems to be heavily used in layers consuming this one (at least most of mine use it). Would be nice to just go ahead and apt-install git in this layer and make it available.

**Comment by chuckbutler** [comment]
-1 to that. If i'm not using git, I've now shipped it as a dependency. I don't think its unreasonable to ask upper layers to install the tools they are consuming, and base-layer to continue only shipping the dependencies for charm operation + boilerplate.

**Comment by marcoceppi** [comment]
I agree with Chuck in general about this . Very little of the charms I've
written use git, a small percentage of the overall charms use git. If it
came down that almost all the charms used git we should have juju just
install it instead. The base layer, in my opinion, should be just enough to
provide building blocks that all charm layers need to work.

**Comment by battlemidget** [comment]
fair enough

**Comment by johnsca** [comment]
Something that does seem like it would be generally useful would be to support a list of apt packages to be installed by the base layer, so that the higher layers can just list packages in a yaml file and have them be installed by the base layer.  The apache-php does this to some extent, but it seems like it would be generally useful.

**Comment by battlemidget** [comment]
Agreed, I use a dependencies.txt file in a few of my layers to handle this. Making this part of the base layer would be a nice addition
